config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

# root to: "public/homes#top"
# top
root 'public/homes#top'
# about
# get 'about' => 'public/homes#about'


namespace :admin do
  resources :orders, only: [:show, :index, :update] do
    resources :order_items, only: [:update]
  end
  resources :genres, only: [:index, :create, :edit, :update]
  resources :items, except: [:destroy]
  resources :customers, only: [:index, :show, :edit, :update]
end

scope module: :public do
  get 'about' => "homes#about", as: 'about'

  resources :cart_items, only:[:index, :update, :destroy, :create] do
    collection do
      delete 'destroy_all'
    end
  end


  resources :items, only: [:index, :show]
  get 'orders/complete', to: 'orders#complete', as: 'complete_order'
  resources :orders, only: [:new, :index, :create, :show]
  post 'orders/confirm(/:id)', to: 'orders#confirm', as: 'confirm_order'


  # resource :customers, only: [:show, :edit, :update]
  get "customers/mypage" => "customers#show"
  get "customers/information/edit" => "customers#edit"
  patch "customers/information" => "customers#update"

  get "customers/unsubscribe" => "customers#unsubscribe"
  patch "customers/withdraw" => "customers#withdraw"

  resources :shipping_addresses, only: [:index, :edit, :create, :update, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items, source: :order

  has_one_attached :image

  validates :name, presence: true
  validates :description, presence: true
  validates :price_without_tax, presence: true, numericality: { only_integer: true }

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.png')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  # 消費税を求める＋桁区切りを行うメソッド
  def price_in_tax
    (price_without_tax * 1.1).floor.to_s(:delimited)
  end

  # 商品価格（税抜）を桁区切りで表示するメソッド
  def price_ex_tax
    price_without_tax.to_s(:delimited)
  end

  # 消費税を求めるメソッド
  def with_tax_price
    (price_without_tax * 1.1).floor
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!
  
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render "error"
    end
  end

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_items_path
    else
      render "error"
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :genre_id, :price_without_tax, :is_active, :image)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/_items_form.html.erb
<div id="error-message">
  <%= render "layouts/errors", obj: item %>
</div>

<%= form_with model: [:admin, item], local: false do |f| %>
  <div class="form-group row offset-md-2">
    <div class="col-sm-2">
      <%= f.label :商品画像 %>
    </div>
    <div class="col-sm-6">
    <%= f.file_field :image, accept: "image/*" %>
    </div>
  </div>

  <div class="form-group row offset-md-2">
    <div class="col-sm-2">
      <%= f.label :商品名 %>
    </div>
    <div class="col-sm-6">
    <%= f.text_field :name, placeholder: "商品名",class: 'form-control item_title' %>
    </div>
  </div>

  <div class="form-group row offset-md-2">
    <div class="col-sm-2">
      <%= f.label :商品説明 %>
    </div>
    <div class="col-sm-6">
      <%= f.text_area :description, placeholder: "ここに説明を記述します", class: 'form-control item_description' %>
    </div>
  </div>

  <div class="form-group row offset-md-2">
    <div class="col-sm-2">
      <%= f.label :ジャンル %>
    </div>
    <div class="col-sm-6">
    <%= f.collection_select :genre_id, Genre.all, :id, :name, {prompt: '--選択してください--'}, class: 'form-control item_genre' %>
    </div>
  </div>

  <div class="form-group row offset-md-2">
    <div class="col-sm-2">
      <%= f.label :税抜価格 %>
    </div>
    <div class="col-sm-6">
    <%= f.text_field :price_without_tax, placeholder: "1000", class: 'form-control item_price' %>
    </div>円
  </div>

  <div class="form-group row offset-md-2">
    <div class="col-sm-2">
      <%= f.label :販売ステータス %>
    </div>
    <div class="col-sm-6">
    <%= f.radio_button :is_active, "true" %>販売中
    <%= f.radio_button :is_active, "false" %>売切れ
    </div>
  </div>

  <div class="form-group text-center">
    <% if params[:id] == nil %>
      <%= f.submit "新規登録", class: 'btn btn-success btn-lg p-2' %>
    <% else %>
      <%= f.submit "編集する", class: 'btn btn-success btn-lg p-2' %>
    <% end %>
  </div>
<% end %>

app/views/admin/items/edit.html.erb
<div class="container">
  <h4 class="my-4 px-4 offset-md-1 d-inline-block", style="background-color: #eee;">商品編集</h4>
  <%= render "items_form", item: @item %>
</div>

app/views/admin/items/error.js.erb
$("#error-message").html("<%= j(render 'layouts/errors', obj: @item) %>");

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-11">
    <h4 class= "my-4 px-4 offset-md-1 d-inline-block", style="background-color: #eee;">商品一覧</h4></div>
    <%= link_to new_admin_item_path do %>
    <div class="col-1"><i class="fas fa-plus-circle fa-3x text-black-50 mt-3"></i></div><% end %>
  </div>
  <table class="table table-borderless table-hover">
    <thead class="thead-light border-top">
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><u><%= link_to item.name, admin_item_path(item), class: "text-reset" %></u></td>
        <td><%= item.price_ex_tax %></td>
        <td><%= item.genre.name %>
        <td class="font-weight-bold"><% if item.is_active == true %>
        <div class="text-success">販売中</div>
        <% else %><div class="text-black-50">販売停止中</div><% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div class="d-flex justify-content-center">
    <%= paginate @items %>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <h4 class="my-4 px-4 offset-md-1 d-inline-block", style="background-color: #eee;">商品新規登録</h4>
  <%= render "items_form", item: @item %>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <h4 class= "my-4 px-4 offset-md-1 d-inline-block", style="background-color: #eee;">商品詳細</h4>
  <div class="row">
    <div class="col-md-4">
      <%= image_tag @item.get_image, size:'320x180' %>
    </div>
    <table class="table table-borderless col-md-8">
      <tr><td style="width: 20%">商品名</td><td class="h5"><%= @item.name %></td></tr>
      <tr><td style="width: 20%">商品説明</td><td class="h5"><%= @item.description %></td></tr>
      <tr><td style="width: 20%">ジャンル</td><td class="h5"><%= @item.genre.name %></td></tr>
      <tr><td style="width: 20%">税込価格<br>（税抜価格）</td>
        <td><h5 class="d-inline-block"><%= @item.price_in_tax %>
        （<%= @item.price_ex_tax %>）</h5>円</td>
      </tr>
      <tr><td style="width: 20%">販売ステータス</td>
        <td class = "font-weight-bold h5">
          <% if @item.is_active == true %>
            <div class = "text-success">販売中</div>
          <% else %>
            <div class = "text-black-50">販売停止中</div><% end %>
        </td>
      </tr>
    </table>
  </div>
  <div class="row text-center">
    <%= link_to "編集する", edit_admin_item_path(@item), class: 'btn btn-success btn-lg p-2 mx-auto' %>
  </div>
</div>