config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

# root to: "public/homes#top"
# top
root 'public/homes#top'
# about
# get 'about' => 'public/homes#about'


namespace :admin do
  resources :orders, only: [:show, :index, :update] do
    resources :order_items, only: [:update]
  end
  resources :genres, only: [:index, :create, :edit, :update]
  resources :items, except: [:destroy]
  resources :customers, only: [:index, :show, :edit, :update]
end

scope module: :public do
  get 'about' => "homes#about", as: 'about'

  resources :cart_items, only:[:index, :update, :destroy, :create] do
    collection do
      delete 'destroy_all'
    end
  end


  resources :items, only: [:index, :show]
  get 'orders/complete', to: 'orders#complete', as: 'complete_order'
  resources :orders, only: [:new, :index, :create, :show]
  post 'orders/confirm(/:id)', to: 'orders#confirm', as: 'confirm_order'


  # resource :customers, only: [:show, :edit, :update]
  get "customers/mypage" => "customers#show"
  get "customers/information/edit" => "customers#edit"
  patch "customers/information" => "customers#update"

  get "customers/unsubscribe" => "customers#unsubscribe"
  patch "customers/withdraw" => "customers#withdraw"

  resources :shipping_addresses, only: [:index, :edit, :create, :update, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy

#特定条件のユーザーのログインを不可にする
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    # @customer = Customer.find(params[:id])
    @customer = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customers_path(@customer.id)
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :phone, :address, :email, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<!DOCTYPE html>
<div class="container">
  <div class="row">
    <div class='col-md-8'>
      <div class="d-inline-block px-3 m-3" style="background-color: #eee;">
        <h3 class="m-0">
        <%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h3>
      </div>

      <%= form_with model: @customer, url: admin_customer_path(@customer), local:true, method: :patch do |f| %>
      <table class="table table-borderless table-sm">
        <div class="field">
          <tr>
          <td><%= f.label :"会員番号" %></td>
          <td colspan='2'><%= @customer.id %></td>
          </tr>
        </div>
        <div class="field">
          <tr>
          <td><%= f.label :"氏名" %></td>
          <td><%= f.text_field :last_name, style: "margin-left:40px;", autocomplete: "first_name" %></td>
          <td><%= f.text_field :first_name, style: "margin-left:40px;",autocomplete: "last_name" %></td>
          </tr>
        </div>

        <div class="field">
          <tr>
          <td><%= f.label :"フリガナ" %></td>
          <td><%= f.text_field :last_name_kana, style: "margin-left:40px;",autocomplete: "first_name_kana" %></td>
          <td><%= f.text_field :first_name_kana,style: "margin-left:40px;", autocomplete: "last_name_kana" %></td>
          </tr>
        </div>

        <div class="field">
          <tr>
          <td><%= f.label :"郵便番号" %></td>
          <td><%= f.text_field :postcode, style: "margin-left:40px;",autocomplete: "postcode" %></td>
          </tr>
        </div>

        <div class="field">
          <tr>
          <td><%= f.label :"住所" %></td>
          <td><%= f.text_field :address, style: "margin-left:40px;",autocomplete: "address" %></td>
          </tr>
        </div>

        <div class="field">
          <tr>
          <td><%= f.label :"電話番号" %></td>
          <td><%= f.telephone_field :phone, style: "margin-left:40px;",autocomplete: "phone" %></td>
          </tr>
        </div>

        <div class="field">
          <tr>
          <td><%= f.label :"メールアドレス" %></td>
          <td><%= f.email_field :email, style: "margin-left:40px;",autocomplete: "email" %></td>
          </tr>
        </div>

        <div class="actions">
          <tr>
          <td>会員ステータス</td>
        　<td>
          　<%= f.radio_button :is_deleted, false, style: "margin-left:40px;" %>
            <%= f.label :is_deleted, "有効", value: :false %>
            <%= f.radio_button :is_deleted, true %>
          　<%= f.label :is_deleted, "退会", value: :true %>
          </td>
          </tr>
        </div>
      <div class="actions">
        <tr>
        <td><br><%= f.submit '変更を保持', class: 'btn btn-success' %></td></tr>
      </div>
    <% end %>
  </table>

app/views/admin/customers/index.html.erb
<div class='container'>
  <div class='row'>
    <div class="d-inline-block px-3 m-3" style="background-color: #eee;">
      <h2 class="m-0">会員一覧</h2>
    </div>

        <table class="table table">
          <thead>
            <tr>
              <th>会員ID</th>
              <th>氏名</th>
              <th>メールアドレス</th>
              <th>ステータス</th>
            </tr>
          </thead>

          <tbody>
            <% @customer.each do |customer| %>
              <tr>
                <td><%= customer.id %></td>
                <td>
                  <%= link_to admin_customer_path(customer), style: "text-decoration: underline;" do%>
                    <%= customer.last_name %>　<%= customer.first_name %>
                  <% end %>
                </td>
                <td><%= customer.email%></td>

                <% if customer.is_deleted == false %>
          　　　　　　<td class = "text-success font-weight-bold">有効</td>
            	  　<%else%>
          　　　　　　<td class = "text-secondary font-weight-bold">退会</td>
            	  <% end %>

              </tr>
            <% end %>
          </tbody>
        </table>

    <div class="row justify-content-center">
      <%= paginate @customer %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<!DOCTYPE html>
<div class="container">
  <div class="row">
    <div class='col-md-8'>
      <div class="d-inline-block px-3 m-3" style="background-color: #eee;">
        <h3 class="m-0">
        <%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h3>
      </div>

      <table class="table table-borderless">
      <tr>
        <td>会員ID</td>
        <td><%= @customer.id %></td>
      </tr>
      <tr>
        <td>氏名</td>
        <td><%= @customer.last_name %>　<%= @customer.first_name %></td>
      </tr>
      <tr>
        <td>フリガナ</td>
        <td><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></td>
      </tr>
       <tr>
        <td>郵便番号</td>
        <td><%= @customer.postcode %></td>
      </tr>
      <tr>
        <td>住所</td>
        <td><%= @customer.address %></td>
      </tr>
      <tr>
        <td>電話番号</td>
        <td><%= @customer.phone %></td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td><%= @customer.email %></td>
      </tr>
      <tr>
        <td>会員ステータス</td>
        <td colspan='2'>
          <% if @customer.is_deleted == true %>
          <div class="text-secondary font-weight-bold">退会</div>
          <% else %>
          <div class="text-success font-weight-bold">有効</div>
          <% end %>
          </td>
      </tr>
        <tfoot>
          <tr>
            <td></td>
            <td><%= link_to "編集する", edit_admin_customer_path,class: "btn btn-success" %></td>
            <td><%= link_to "注文履歴一覧を見る", admin_orders_path,class: "btn btn-primary" %></td>
          </tr>
        </tfoot>
    </table>
  </div>
 </div>
</div>

app/views/admin/customers/update.html.erb
<h1>Admin::Customers#update</h1>
<p>Find me in app/views/admin/customers/update.html.erb</p>