config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

# root to: "public/homes#top"
# top
root 'public/homes#top'
# about
# get 'about' => 'public/homes#about'


namespace :admin do
  resources :orders, only: [:show, :index, :update] do
    resources :order_items, only: [:update]
  end
  resources :genres, only: [:index, :create, :edit, :update]
  resources :items, except: [:destroy]
  resources :customers, only: [:index, :show, :edit, :update]
end

scope module: :public do
  get 'about' => "homes#about", as: 'about'

  resources :cart_items, only:[:index, :update, :destroy, :create] do
    collection do
      delete 'destroy_all'
    end
  end


  resources :items, only: [:index, :show]
  get 'orders/complete', to: 'orders#complete', as: 'complete_order'
  resources :orders, only: [:new, :index, :create, :show]
  post 'orders/confirm(/:id)', to: 'orders#confirm', as: 'confirm_order'


  # resource :customers, only: [:show, :edit, :update]
  get "customers/mypage" => "customers#show"
  get "customers/information/edit" => "customers#edit"
  patch "customers/information" => "customers#update"

  get "customers/unsubscribe" => "customers#unsubscribe"
  patch "customers/withdraw" => "customers#withdraw"

  resources :shipping_addresses, only: [:index, :edit, :create, :update, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items, source: :item

  # enumで支払い方法定義
  enum payment_method: { credit_card: 0, transfer: 1 }

  # 注文ステータス定義
  enum order_status: {
    "waiting_payment":0,
    "payment_confirmation":1,
    "production":2,
    "shipping_preparation":3,
    "sent":4
  }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    if params[:id]
      @orders = Customer.find(params[:id]).orders.page(params[:page]).per(10)
    elsif request.fullpath.include? "today"
      @orders = Order.where(created_at:  Time.zone.now.all_day).page(params[:page]).per(10)
    elsif request.fullpath.include? "yesterday"
      @orders = Order.where(created_at: 1.day.ago.all_day).page(params[:page]).per(10)
    else
      @orders = Order.page(params[:page]).per(10)
    end
  end

  def show
    @order = Order.find(params[:id])
    @order_item = OrderItem.where(order_id: @order.id)
    @customer = @order.customer
  end

  def update
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    if @order.update(order_params)
      if @order.order_status == "payment_confirmation"
        @order_items.each do |order_item|
          order_item.update(production_status: "waiting_for_making")
        end
      end
      redirect_to admin_order_path
    else
      redirect_to admin_order_path
    end
  end

  protected

  def order_params
    params.require(:order).permit(:customer_id, :postage, :billing_amount, :payment_method, :name, :address, :postcode ,:order_status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
  <div class='row'>
    <div class="d-inline-block px-3 m-3" style="background-color: #eee;">
      <h4 class="m-0">注文履歴一覧</h4>
    </div>

  	<table class="table table-hover">
  	  <thead class="thead-light table-bordered">
    	  <tr>
          <th>購入日時</th>
          <th>購入者</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
      </thead>
      <% @orders.each do |order| %>
        <tr>
          <td>
            <%= link_to admin_order_path(order.id) do %>
              <%= l order.created_at, format: :short %>
            <% end %>
          </td>
          <td><%= order.customer.last_name %><%= order.customer.first_name %></td>
          <td>
            <!--注文個数の計算-->
            <% @order_total_quantity = 0 %>
            <% order.order_items.each do |order_item| %>
              <% @order_total_quantity += order_item.quantity %>
            <% end %>
            <!--表示-->
            <%= @order_total_quantity %>
          </td>
          <td><%= order.order_status_i18n %></td>
        </tr>
      <% end %>
    </table>
  </div>

  <div class="row m-3 justify-content-center">
    <%= paginate @orders %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
    <div class="d-inline-block px-3 m-3" style="background-color: #eee;">
      <h4 class="m-0">注文履歴詳細</h4>
    </div>
      <!-- 購入詳細情報 -->
      <div class="mb-4">
        <table>
          <tr>
            <th>購入者</th>
            <td class="pl-4">
              <!--%= link_to admin_customer_path(@customer.id) do %>-->
                <%= @order.customer.last_name %> <%= @order.customer.first_name %>
              <!--% end %>-->
            </td>
          </tr>
          <tr>
            <th>注文日</th>
            <td class="pl-4"><%= l @order.created_at %></td>
          </tr>
          <tr>
            <th style="vertical-align: top;">配送先</th>
            <td class="pl-4">〒<%= @order.postcode %> <%= @order.address %><br><%= @order.name %></td>
          </tr>
          <tr>
            <th>支払い方法</th>
            <td class="pl-4"><%= @order.payment_method_i18n %></td>
          </tr>
          <tr>
            <!-- 注文ステータス変更 プルダウン 更新を押すとアップデート -->
            <th>注文ステータス</th>
            <td class="pl-4">
              <%= form_with model: @order, url: admin_order_path do |f| %><!--oreder controllerのupdateの飛ぶ-->
                <%= f.select :order_status, Order.order_statuses_i18n.invert, {}, placeholder: 0 %>
                <%= f.submit "更新" ,class: "btn btn-primary btn-sm" %>
              <% end %>
            </td>
          </tr>
        </table>
      </div>

      <div class="row">
    <div class="col-xs-6 mr-5">
      <table class="table table-hover">
        <thead class="thead-light border-top">
        <tr>
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
          <th></th>
        </tr>
        </thead>
        <% @order_item.each do |order_item| %><!--注文した商品の履歴一覧をeach分で表示 -->
        <tr>
          <td><%= order_item.item.name %></td>
          <td><%= ((order_item.item.price_without_tax)*1.1).floor.to_s(:delimited)  %></td>
          <td><%= order_item.quantity %></td>
          <td><%= ((order_item.item.price_without_tax)*1.1*(order_item.quantity)).floor.to_s(:delimited)  %> </td>
        <!-- 製作ステータス変更 更新を押すと更新-->
        <!-- rails routesでorder_itemを確認すると、order:idとorder_item:idが必要であるため、form_withのモデルとurlにそれぞれ指定する -->
          <%= form_with model: [@order,order_item] , url: admin_order_order_item_path(@order, order_item), method: :patch, local: true  do |f| %>
          <!--入力は日本語でよくて、値を送信するときは英語で送信する必要がある 調べ方：enum select もしくはenum pulldown -->
          <!--<td>%= f.select :production_status,["着手不可","製作待ち","製作中","製作完了"] %></td>ステータス選択 -->
          <td><%= f.select :production_status, OrderItem.production_statuses_i18n.invert, {}, placeholder: 0 %></td>

          <td><%= f.submit "更新" ,class:"btn btn-primary btn-xs" %></td>
          <% end %>
        </tr>
          <% end %>
      </table>
    </div>

    <div class="col-xs-4">
     <h5><strong>商品合計</strong>　　　<%= (@order.billing_amount-@order.postage).to_s(:delimited)  %>円</h4>
     <h5><strong>送料</strong>　　　　　<%= @order.postage.to_s(:delimited) %>円</h4>
     <h5><strong>請求金額合計　<%= @order.billing_amount.to_s(:delimited) %>円</strong></h4>
    </div>
  </div>
</div>