config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

# root to: "public/homes#top"
# top
root 'public/homes#top'
# about
# get 'about' => 'public/homes#about'


namespace :admin do
  resources :orders, only: [:show, :index, :update] do
    resources :order_items, only: [:update]
  end
  resources :genres, only: [:index, :create, :edit, :update]
  resources :items, except: [:destroy]
  resources :customers, only: [:index, :show, :edit, :update]
end

scope module: :public do
  get 'about' => "homes#about", as: 'about'

  resources :cart_items, only:[:index, :update, :destroy, :create] do
    collection do
      delete 'destroy_all'
    end
  end


  resources :items, only: [:index, :show]
  get 'orders/complete', to: 'orders#complete', as: 'complete_order'
  resources :orders, only: [:new, :index, :create, :show]
  post 'orders/confirm(/:id)', to: 'orders#confirm', as: 'confirm_order'


  # resource :customers, only: [:show, :edit, :update]
  get "customers/mypage" => "customers#show"
  get "customers/information/edit" => "customers#edit"
  patch "customers/information" => "customers#update"

  get "customers/unsubscribe" => "customers#unsubscribe"
  patch "customers/withdraw" => "customers#withdraw"

  resources :shipping_addresses, only: [:index, :edit, :create, :update, :destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  validates :quantity, presence: true
  
  # 小計を求めるメソッド
  def subtotal
    item.with_tax_price * quantity
  end 
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy

#特定条件のユーザーのログインを不可にする
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, uniqueness: true, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items, source: :order

  has_one_attached :image

  validates :name, presence: true
  validates :description, presence: true
  validates :price_without_tax, presence: true, numericality: { only_integer: true }

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.png')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  # 消費税を求める＋桁区切りを行うメソッド
  def price_in_tax
    (price_without_tax * 1.1).floor.to_s(:delimited)
  end

  # 商品価格（税抜）を桁区切りで表示するメソッド
  def price_ex_tax
    price_without_tax.to_s(:delimited)
  end

  # 消費税を求めるメソッド
  def with_tax_price
    (price_without_tax * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items, source: :item

  # enumで支払い方法定義
  enum payment_method: { credit_card: 0, transfer: 1 }

  # 注文ステータス定義
  enum order_status: {
    "waiting_payment":0,
    "payment_confirmation":1,
    "production":2,
    "shipping_preparation":3,
    "sent":4
  }
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }

  # 注文ステータス定義
  enum production_status: {
    "impossible_making":0,
    "waiting_for_making":1,
    "making":2,
    "complete":3,
  }
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :customer

  validates :name, presence: true
  validates :postcode, presence: true, numericality: { only_integer: true }
  validates :address, presence: true

  def address_display
    postcode + " " + address + " " + name
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end 
  
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end 
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end 
  
  private
  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!
  
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render "error"
    end
  end

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_items_path
    else
      render "error"
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :genre_id, :price_without_tax, :is_active, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private
    def after_sign_in_path_for(resource_or_scope)
      if resource_or_scope.is_a?(Admin)
        admin_orders_path
      else
        root_path
      end
    end

  def
    after_sign_out_path_for(resource_or_scope)
      if resource_or_scope == :customer
          root_path
      elsif resource_or_scope == :admin
          new_admin_session_path
      else
          root_path
      end
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation", class="alert alert-danger" role="alert">
    <h3>入力を確認してください</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCAKE</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="border-bottom", style="background-color: #dcdcdc">
      <nav class="navbar navbar-expand-lg ">
        <div class="container">
          <a class="navbar" href="/"><%= image_tag "/assets/Logo.png", size: "280x85" %></a>
           <div class="collapse navbar-collapse row" id="navbarNavDropdown">

            <!--顧客用ヘッダー-->
            <% if customer_signed_in? %>

                 <h5 class="ml-5">ようこそ、<%= current_customer.last_name %>さん!</h5>

                 <ul class="navbar-nav ml-auto">
                  <li class ="rounded border border-dark mr-5 bg-light"><%= link_to "マイページ", customers_mypage_path,class: 'nav-link text-dark' %></li>
                  <li class ="rounded border border-dark mr-5 bg-light"><%= link_to "商品一覧", items_path,class: 'nav-link text-dark' %></li>
                  <li class ="rounded border border-dark mr-5 bg-light"><%= link_to "カート", cart_items_path,class: 'nav-link text-dark' %></li>
                  <li class ="rounded border border-dark mr-5 bg-light"><%= link_to "ログアウト",  destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %></li>
                </ul>

            <!--管理者用ヘッダー-->
            <% elsif admin_signed_in?  %>

               <ul class="navbar-nav ml-auto">
                  <li class ="rounded border border-dark mr-3 bg-light"><%= link_to "商品一覧", admin_items_path, class: 'nav-link text-dark'%></li>

                  <li class ="rounded border border-dark mr-3 bg-light"><%= link_to "注文履歴一覧", admin_orders_path, class: 'nav-link text-dark'%></li>
                  <li class ="rounded border border-dark mr-3 bg-light"><%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-dark'%></li>

                  <li class ="rounded border border-dark mr-3 bg-light"><%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-dark'%></li>
                  <li class ="rounded border border-dark mr-3 bg-light"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete,class: 'nav-link text-dark'%></li>
               </ul>

            <!--ログイン前ヘッダー-->
            <% else %>

                 <ul class="navbar-nav ml-auto">
                  <li class ="rounded border border-dark mr-5 bg-light"><%= link_to "About", about_path,class: 'nav-link text-dark'%></li>
                  <li class ="rounded border border-dark mr-5 bg-light"><%= link_to "商品一覧", items_path,class: 'nav-link text-dark'%></li>
                  <li class ="rounded border border-dark mr-5 bg-light"><%= link_to "新規登録", new_customer_registration_path,class: 'nav-link text-dark' %></li>
                  <li class ="rounded border border-dark mr-5 bg-light"><%= link_to "ログイン", new_customer_session_path,class: 'nav-link text-dark' %></li>
                 </ul>

            <% end %>
          <!--検索フォーム-->
              <div class="container justify-content-end pt-3">
                <div class="row">
                  <div class="col-ml-auto mr-4">
                    <%= form_with url: items_path, method: :get do |f| %>
                    <div class="input-group">
                      <%= f.text_field :word, placeholder: "Search", class: "input-group-prepend" %>
                      <span class="input-group-btn">
                        <%= f.button :type => "submit" do %><i class="fas fa-search"></i><% end %>
                      </span>
                    </div>
                    <% end %>
                  </div>
                </div>
              </div>
          <!--検索フォームここまで-->
            </div>
          </div>
        </nav>
    
    
    </header>
    
    <!--ヘッダーと被らないようにする-->
    <body style="padding-bottom:4rem">
    </body>
    
    <%= yield %>
    <footer class="fixed-bottom" style="background-color: #dcdcdc">
      <div style="padding: 5px;">
        <h6 class="text-dark text-center mr-3" id="footer_logo"><small>©naganoCAKE</small></h6>
      </div>
    </footer>
  </body>
</html>